spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: xuoj-backend-user-service
          uri: lb://xuoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: xuoj-backend-question-service
          uri: lb://xuoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: xuoj-backend-judge-service
          uri: lb://xuoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: xuoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101

knife4j:
  gateway:
    # 开启gateway聚合组件
    enabled: true
    # 设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # 开启discover模式
      enabled: true
      # 聚合子服务全部为Swagger2规范的文档
      version: swagger2



############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: xToken
  # token 有效期（单位：秒） 默认7天，-1 代表永久有效
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 未登录场景下获取 Token-Session
  token-session-check-login: false
